In [1]:
import pandas as pd      
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

from scipy.stats import skew

from sklearn.model_selection import cross_validate, cross_val_score
import warnings
warnings.filterwarnings('ignore')
plt.rcParams["figure.figsize"] = (10,6)
pd.set_option('display.max_columns', 500) 
pd.set_option('display.max_rows', 500)

In [2]:
df = pd.read_excel("Raisin_Dataset.xlsx")

In [3]:
df.groupby("Class").describe().T

Class                          Besni        Kecimen
Area            count     450.000000     450.000000
                mean   112194.788889   63413.466667
                std     39229.897872   17727.768795
                min     40702.000000   25387.000000
                25%     83598.500000   50466.250000
                50%    104426.500000   61420.000000
                75%    135683.250000   75153.000000
                max    235047.000000  180898.000000
MajorAxisLength count     450.000000     450.000000
                mean      509.000652     352.859249
                std       105.771154      59.611494
                min       274.168954     225.629541
                25%       436.546027     313.535782
                50%       493.185891     350.234107
                75%       582.386571     390.361570
                max       997.291941     843.956653
MinorAxisLength count     450.000000     450.000000
                mean      279.623674     229.352592
                std        50.763657      34.058657
                min       172.508389     143.710872
                25%       242.640411     205.197075
                50%       273.367137     228.619791
                75%       308.306117     250.785159
                max       492.275279     326.898724
Eccentricity    count     450.000000     450.000000
                mean        0.821125       0.741960
                std         0.068277       0.092362
                min         0.500991       0.348730
                25%         0.787999       0.704251
                50%         0.831953       0.766472
                75%         0.868839       0.801992
                max         0.962124       0.923770
ConvexArea      count     450.000000     450.000000
                mean   116675.824444   65696.355556
                std     40797.067805   19005.891848
                min     41924.000000   26139.000000
                25%     87668.000000   52115.000000
                50%    108062.500000   63826.500000
                75%    139779.750000   77504.250000
                max    278217.000000  221396.000000
Extent          count     450.000000     450.000000
                mean        0.691242       0.707774
                std         0.060827       0.043442
                min         0.379856       0.454189
                25%         0.656343       0.680811
                50%         0.702900       0.710321
                75%         0.733543       0.737583
                max         0.830632       0.835455
Perimeter       count     450.000000     450.000000
                mean     1348.127036     983.686236
                std       246.804611     150.305531
                min       771.797000     619.074000
                25%      1182.345750     885.148500
                50%      1305.799500     977.929500
                75%      1510.482500    1073.222750
                max      2697.753000    2253.557000

In [4]:
df["class_bin"] = np.where(df.Class == "Kecimen", 0, 1)
df.head()

Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
0  87524       442.246011       253.291155      0.819738       90546   
1  75166       406.690687       243.032436      0.801805       78789   
2  90856       442.267048       266.328318      0.798354       93717   
3  45928       286.540559       208.760042      0.684989       47336   
4  79408       352.190770       290.827533      0.564011       81463   

     Extent  Perimeter    Class  class_bin  
0  0.758651   1184.040  Kecimen          0  
1  0.684130   1121.786  Kecimen          0  
2  0.637613   1208.575  Kecimen          0  
3  0.699599    844.162  Kecimen          0  
4  0.792772   1073.251  Kecimen          0

In [5]:
df = df.drop("Class", axis = 1); df.head()

Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
0  87524       442.246011       253.291155      0.819738       90546   
1  75166       406.690687       243.032436      0.801805       78789   
2  90856       442.267048       266.328318      0.798354       93717   
3  45928       286.540559       208.760042      0.684989       47336   
4  79408       352.190770       290.827533      0.564011       81463   

     Extent  Perimeter  class_bin  
0  0.758651   1184.040          0  
1  0.684130   1121.786          0  
2  0.637613   1208.575          0  
3  0.699599    844.162          0  
4  0.792772   1073.251          0

In [6]:
X= df.drop(columns="class_bin")
y= df.class_bin
print(X,y)

      Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
0    87524       442.246011       253.291155      0.819738       90546   
1    75166       406.690687       243.032436      0.801805       78789   
2    90856       442.267048       266.328318      0.798354       93717   
3    45928       286.540559       208.760042      0.684989       47336   
4    79408       352.190770       290.827533      0.564011       81463   
..     ...              ...              ...           ...         ...   
895  83248       430.077308       247.838695      0.817263       85839   
896  87350       440.735698       259.293149      0.808629       90899   
897  99657       431.706981       298.837323      0.721684      106264   
898  93523       476.344094       254.176054      0.845739       97653   
899  85609       512.081774       215.271976      0.907345       89197   

       Extent  Perimeter  
0    0.758651   1184.040  
1    0.684130   1121.786  
2    0.637613   1208.575  
3  

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [8]:
scaler = StandardScaler()

In [9]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
log_model = LogisticRegression()

In [12]:
log_model.fit(X_train_scaled, y_train)

LogisticRegression()

In [13]:
y_pred = log_model.predict(X_test_scaled)

In [14]:
y_pred_proba = log_model.predict_proba(X_test_scaled)

In [15]:
test_data = pd.concat([X_test, y_test], axis=1)
test_data["pred"] = y_pred
test_data["pred_proba"] = y_pred_proba[:,1]#1 olma olasılığı
test_data.sample(10)

Area  MajorAxisLength  MinorAxisLength  Eccentricity  ConvexArea  \
227   65469       374.466231       227.538997      0.794216       68018   
753   79057       436.390047       236.895393      0.839828       82642   
454   61409       403.701295       209.365889      0.855007       67286   
629   83059       440.559971       243.636512      0.833171       88806   
333   60313       339.603456       227.725924      0.741851       62130   
89    49059       301.800398       210.467215      0.716709       50835   
319   57303       330.024964       221.919786      0.740158       58973   
620   78984       427.494276       236.882575      0.832438       82328   
871  105091       507.685116       268.087343      0.849208      108296   
299   36113       257.641853       181.157079      0.711056       37442   

       Extent  Perimeter  class_bin  pred  pred_proba  
227  0.714438   1020.029          0     0    0.228485  
753  0.654597   1148.146          1     1    0.627172  
454  0.597393   1083.477          1     0    0.485899  
629  0.685809   1238.163          1     1    0.780822  
333  0.726680    946.487          0     0    0.094078  
89   0.698607    867.582          0     0    0.040899  
319  0.716762    919.044          0     0    0.074011  
620  0.698417   1169.476          1     1    0.640883  
871  0.700271   1295.591          1     1    0.900593  
299  0.694481    737.637          0     0    0.012288

In [16]:
from sklearn.metrics import confusion_matrix, classification_report

In [17]:
def eval_metric(model, X_train, y_train, X_test, y_test):
    y_train_pred = model.predict(X_train)
    y_pred = model.predict(X_test)
    
    print("Test_Set")
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print()
    print("Train_Set")
    print(confusion_matrix(y_train, y_train_pred))
    print(classification_report(y_train, y_train_pred))

In [18]:
eval_metric(log_model, X_train_scaled, y_train, X_test_scaled, y_test)

Test_Set
[[127  13]
 [ 24 106]]
              precision    recall  f1-score   support

           0       0.84      0.91      0.87       140
           1       0.89      0.82      0.85       130

    accuracy                           0.86       270
   macro avg       0.87      0.86      0.86       270
weighted avg       0.86      0.86      0.86       270


Train_Set
[[275  35]
 [ 47 273]]
              precision    recall  f1-score   support

           0       0.85      0.89      0.87       310
           1       0.89      0.85      0.87       320

    accuracy                           0.87       630
   macro avg       0.87      0.87      0.87       630
weighted avg       0.87      0.87      0.87       630



In [19]:
from sklearn.model_selection import cross_validate

In [20]:
model = LogisticRegression()

scores = cross_validate(model, X_train_scaled, y_train, scoring = ['precision','recall','f1','accuracy'], cv = 5)
df_scores = pd.DataFrame(scores, index = range(1, 6))
df_scores

fit_time  score_time  test_precision  test_recall   test_f1  test_accuracy
1  0.007978    0.003997        0.870968     0.843750  0.857143       0.857143
2  0.003998    0.003998        0.918033     0.875000  0.896000       0.896825
3  0.005990    0.002991        0.866667     0.812500  0.838710       0.841270
4  0.004997    0.004001        0.885246     0.843750  0.864000       0.865079
5  0.017004    0.007995        0.887097     0.859375  0.873016       0.873016

In [21]:
df_scores.mean()[2:]

test_precision    0.885602
test_recall       0.846875
test_f1           0.865774
test_accuracy     0.866667
dtype: float64

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
#GridSearchCV ile recall iyileştirmek için parametreleri ve değerleri ayarlayıp  1 skorunun değerini iyileştirip hastalaı yakalama oranını artırmak. 

model = LogisticRegression()

penalty = ["l1", "l2", "elasticnet"]
C = np.logspace(-3,3,7) # katsayı için logspace alınarak değerler verilmesi öneriliyor


param_grid = {"penalty" : penalty,
              "C" : C
             }


grid_model = GridSearchCV(estimator=model,
                          param_grid=param_grid,
                          cv=10,
                          scoring = "recall", # 1 class ait en iyi skoru döndürecek, tek score verebiliriz
                          n_jobs = -1)

In [24]:
grid_model.fit(X_train_scaled, y_train)

GridSearchCV(cv=10, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='recall')

In [25]:
grid_model.best_params_

{'C': 1.0, 'penalty': 'l2'}

In [26]:
eval_metric(grid_model, X_train_scaled, y_train, X_test_scaled, y_test)

Test_Set
[[127  13]
 [ 24 106]]
              precision    recall  f1-score   support

           0       0.84      0.91      0.87       140
           1       0.89      0.82      0.85       130

    accuracy                           0.86       270
   macro avg       0.87      0.86      0.86       270
weighted avg       0.86      0.86      0.86       270


Train_Set
[[275  35]
 [ 47 273]]
              precision    recall  f1-score   support

           0       0.85      0.89      0.87       310
           1       0.89      0.85      0.87       320

    accuracy                           0.87       630
   macro avg       0.87      0.87      0.87       630
weighted avg       0.87      0.87      0.87       630

